version: '3'
services:
  blue:
    container_name: blue
    image: whereami2048/blue-green
    expose:
      - 8080
    ports:
      - "8080:8080"

  green:
    container_name: green
    image: whereami2048/blue-green
    expose:
      - 8080
    ports:
      - "8081:8080"